### ISSUE TITLE
not python2.7 compatible

### ISSUE THREAD

**Issue by ghost** [podhmo/json2swagger#4]
I just ran into this using python2.7 - just wanted to let you know :)

``` bash
$ json2swagger -h
Traceback (most recent call last):
  File "/Users/fin0007m/devel/gcdt/bvenv/bin/json2swagger", line 7, in <module>
    from json2swagger import main
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/json2swagger/__init__.py", line 194
    print("# *", end="")
                    ^
SyntaxError: invalid syntax
```

...but using python3 it turns out useful. thank you!

**Comment by podhmo** [comment]
thx.
But, honestly, I haven't the motivation supporting python2.x, sorry.
